package org.acme.quartz;

public enum JobName {
    SPARKPOST_RAW_BATCH_MESSAGE_PROCESSOR,
    SPARKPOST_EVENT_PROCESSOR,
    STRIPE_RAW_MESSAGE_PROCESSOR,
    SUBSCRIBER_STATUS_EVENT_PROCESSOR,
    FORM_EVENT_PROCESSOR,
    LIFE_CYCLE_EVENT_PROCESSOR;
}
